theme="monokai_pro"
[editor]
true-color=true
bufferline="multiple"
cursorline=true
rulers=[120]
[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"
[editor.indent-guides]
character="╎"
render=true
[editor.file-picker]
hidden=false
[editor.statusline]
left=["mode", "spinner", "version-control", "file-name"]
separator="|"
